This file contains deployment related stuff..
Updated this file....
<<<<<<< HEAD
Updating this code.....
This line is added for testing....
=======
>>>>>>> parent of dc6120a (Updated Deploy.sh)
aaaaaaaaaaaaaaaaaaa
